sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

language: node_js
node_js:
  - "0.12"

services:
  - docker

before_install:
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - gulp

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export DOCKER_REPO=vuzoll/vuzoll-webui
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
  - docker build -t $DOCKER_REPO:$COMMIT .
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO
